services:
  db:
    image: mysql:8.0.45-debian
    container_name: mysql_furnitureshop
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: furnitureshop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network
    restart: unless-stopped

  redis:
    image: redis:trixie
    container_name: redis_furnitureshop
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redisinsight_furnitureshop
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    networks:
      - backend_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_furnitureshop
    environment:
      RABBITMQ_DEFAULT_USER: ${SPRING_RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${SPRING_RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend_network
    restart: unless-stopped

  clamav:
    image: dhi.io/clamav:1.5-base
    container_name: clamav_furnitureshop
    ports:
      - "3310:3310"
    networks:
      - backend_network
    restart: unless-stopped

  minio:
    image: quay.io/minio/aistor/minio:RELEASE.2026-05-04T23-02-27Z
    container_name: minio_furnitureshop
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_NAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker-data/minio:/data
      - "${MINIO_LICENSE_PATH}:/license/minio.license:ro"
    command: >
      server /data 
      --console-address ":9001"
      --license /license/minio.license
    networks:
      - backend_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  redisinsight:
  rabbitmq_data:

networks:
  backend_network:
    driver: bridge