spring.application.name=furnitureshop

server.port=${SERVER_PORT}

# Configuration of MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration of Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# Configuration of email service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Secret key of Turnstile
#turnstile.secret-key=0x4AAAAAACn2wSz_pZRy1OGnF0CBRgu9pqc
turnstile.secret-key=${TURNSTILE_SECRET-KEY}

# ========== Configuration of RabbitMQ ==========
# 1. RabbitMQ Connection
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL-HOST}

# 2. Publisher confirms for reliability
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# 3. Listener configuration
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=10
# Retry
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.multiplier=2.0
# ========== End of RabbitMQ Configuration ==========


# ========== Properties of notification services ==========
# Exchange
notification-service.mq.exchange=notification.exchange

# Queues
notification-service.mq.email-queue=notification.email.queue
notification-service.mq.inapp-queue=notification.inapp.queue

# Routing Keys
notification-service.mq.email-routing-key=notification.email
notification-service.mq.inapp-routing-key=notification.inapp
# ========== End of Setting up Properties of notification services ==========


# Jwt
secret-key=${SECRET-KEY}
# seconds
jwt.expiry-time.access-token-minutes=15
jwt.expiry-time.refresh-token-days=30

# Regex for validation
user.password.regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=_]).{8,}$


# Configuration properties of Permission caching:
rbac-cache.prefix-key=rbac
rbac-cache.roles-permissions-ttl-days=30

# MultipartFile config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

file.root-path=${FILE_ROOT-PATH}
app.base-url=${APP_BASE-URL}

#ClamAV attributes:
clamav.host=${CLAMAV_HOST}
clamav.port=${CLAMAV_PORT}